services:
  - type: web
    name: fullstack-app
    env: docker
    image:
      url: ghcr.io/uoriou/app-image:latest
      creds:
        fromRegistry: github-cr
    plan: free
    autoDeploy: true

